export const GET_ALL_COMPETITIONS_REQUEST = 'GET_ALL_COMPETITIONS_REQUEST';

export const GET_TEAMS_FROM_COMPETITION_REQUEST = 'GET_TEAMS_FROM_COMPETITION_REQUEST';
export const SET_TEAMS_FROM_COMPETITION = 'SET_TEAMS_FROM_COMPETITION';
